# Generated by Django 3.1.4 on 2021-01-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='images')),
                ('item_price', models.FloatField(verbose_name='Price')),
                ('item_description', models.CharField(max_length=300)),
            ],
        ),
    ]
