# Generated by Django 3.1.4 on 2021-01-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('caps', 'Caps'), ('coats', 'Coats'), ('hats', 'Hats'), ('hoodies', 'Hoodies'), ('jackets', 'Jackets'), ('jackets', 'Jackets'), ('shirts', 'Shirts'), ('skits', 'Shirts'), ('sweaters', 'Sweaters'), ('waistcoats', 'Waistcoats')], default='Please Select Type of Item', max_length=30),
        ),
    ]
