# Generated by Django 3.1.4 on 2021-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20210129_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
