# Generated by Django 3.1.4 on 2021-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20210228_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Image',
            field=models.ImageField(upload_to='static/img/collections'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_Price',
            field=models.FloatField(verbose_name='Price (ZAR)'),
        ),
    ]
